In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
outlook = ['sunny', 'sunny', 'overcast', 'rain', 'rain', 'rain', 'overcast', 'sunny', 'sunny', 'rain', 'sunny', 'overcast', 'overcast', 'rain']
temp = ['hot', 'hot', 'hot', 'mild', 'cool', 'cool', 'cool', 'mild', 'cool', 'mild', 'mild', 'mild', 'hot', 'mild']
humidity = ['high', 'high', 'high', 'high', 'normal', 'normal', 'normal', 'high', 'normal', 'normal', 'normal', 'high', 'normal', 'high']
wind = ['weak', 'strong', 'weak', 'weak', 'weak', 'strong', 'strong', 'weak', 'weak', 'weak', 'strong', 'strong', 'weak', 'strong']
play_tennis = [0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0]

df = pd.DataFrame(data=list(zip(outlook, temp, humidity, wind, play_tennis)), columns=['outlook', 'temp', 'humidity', 'wind', 'play_tennis'])
df

     outlook  temp humidity    wind  play_tennis
0      sunny   hot     high    weak            0
1      sunny   hot     high  strong            0
2   overcast   hot     high    weak            1
3       rain  mild     high    weak            1
4       rain  cool   normal    weak            1
5       rain  cool   normal  strong            0
6   overcast  cool   normal  strong            1
7      sunny  mild     high    weak            0
8      sunny  cool   normal    weak            1
9       rain  mild   normal    weak            1
10     sunny  mild   normal  strong            1
11  overcast  mild     high  strong            1
12  overcast   hot   normal    weak            1
13      rain  mild     high  strong            0

In [49]:
# Calculate entropy of whole data set (s)
# s can be either 0 or 1.
zeros_count = 5
yes_count = 9

# Calculate information gain of each and every attribute
entropy_s = -1.0 * 9/14 * np.log2(9/14) + (-1.0 * 5/14 * np.log2(5/14))
print("Entropy(S) : ", entropy_s)

# Calculate entropy for feature 1 : outlook.
# sunny has 3 0's and 2 1's.
entropy_sunny = -1.0 * 2/5 * np.log2(2/5) + (-1.0 * 3/5 * np.log2(3/5))

# overcast has 4 1's and 0 0's.
entropy_overcast = -1.0 * 4/4 * np.log2(4/4) 

# rain has 3 1's and 2 0's.
entropy_rain = -1.0 * 3/5 * np.log2(3/5) + (-1.0 * 2/5 * np.log2(2/5))

entropy_outlook =  5/14.0 * entropy_sunny + 4/14.0 * entropy_overcast + 5/14.0 * entropy_rain

print("Entropy outlook : ", entropy_outlook)
ig_outlook = entropy_s - entropy_outlook
print("IG : outlook : ", ig_outlook)

Entropy(S) :  0.9402859586706311
Entropy outlook :  0.6935361388961918
IG : outlook :  0.24674981977443933